// ╔══════════════════════════════════════════════════════════════════╗
// ║  BillerHeader.jsx — Enterprise POS Header v17                   ║
// ║  ✅ FIXED: Dark mode button visibility (gold/white borders)     ║
// ║  ✅ FIXED: Icon buttons now have visible labels                 ║
// ║  ✅ FIXED: Full English/Urdu translation support                ║
// ╚══════════════════════════════════════════════════════════════════╝

import {
  useState, useRef, useCallback,
  useEffect, useMemo, memo,
} from 'react';
import { useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Search, UserPlus, User, X, Wifi, WifiOff,
  Volume2, VolumeX, Hash, Clock, Lock, Unlock,
  Loader2, Phone, MapPin, Database, ChevronDown,
  Sun, Moon, Languages, LogOut, Settings, Gem,
  Menu, CreditCard, ShoppingBag, Download, Trash2,
  Crown, ShieldCheck, Users, Receipt, Building2,
  CheckCircle2, Clock3, Plus, Package,
  Eye, EyeOff, Zap, MoreHorizontal, Bell,
  Mic, MicOff, Music, Calculator,
} from 'lucide-react';
import {
  collection, query, where, limit,
  onSnapshot, getDocs, orderBy, doc,
} from '../../services/firebase';
import toast from 'react-hot-toast';

import { db } from '../../services/firebase';
import { db as localDb } from '../../db/index';
import { getRecentOrders } from '../../services/localBillService';
import { useTheme } from '../../context/ThemeContext';
import { useLanguage } from '../../hooks/useLanguage';
import { useAuth } from '../../context/AuthContext';
import { useNetwork } from '../../context/NetworkContext';
import { useNextSerial } from '../../hooks/useNextSerial';
import { useSound } from '../../hooks/useSound';
import {
  cacheLoad,
  cacheSearch,
  isValidCustomer,
} from '../../components/biller/CustomerDialog';
import {
  resolveCustomerName,
  buildCustomerObject,
  isAutoGeneratedName,
  normalizePhone,
} from '../../utils/customerUtils';
import { ROLE_INFO } from '../../utils/rolePermissions';
import { cn } from '../../utils/cn';
import { relativeTime, toSafeDate } from '../../utils/dateHelpers';

// ══════════════════════════════════════════════════════════════
// CONSTANTS
// ══════════════════════════════════════════════════════════════
const CACHE_TTL_MS = 5 * 60 * 1000;
const SEARCH_DEBOUNCE_MS = 150;
const MAX_TABS = 10;
const TOP5_CACHE_PREFIX = 'pos_top5_';
const BILLING_CHANNEL = 'aone_pos_billing';
const ORDERS_CHANNEL = 'aone_pos_orders';

// ══════════════════════════════════════════════════════════════
// TRANSLATIONS — Full English/Urdu support
// ══════════════════════════════════════════════════════════════
const T = {
  en: {
    posSystem: 'POS System',
    online: 'Online',
    offline: 'Offline',
    locked: 'LOCKED',
    active: 'ACTIVE',
    item: 'item',
    items: 'items',
    loading: 'Loading',
    next: 'Next',
    cashier: 'Cashier',
    customer: 'Customer',
    addCustomer: 'Add Customer',
    search: 'Search',
    searchPlaceholder: 'Search customer by phone or name…',
    noCustomerFound: 'No customer found for',
    addNewCustomer: 'Add New Customer',
    sound: 'Sound',
    soundOn: 'Sound ON',
    soundOff: 'Sound OFF',
    soundControls: 'Sound Controls',
    soundEvents: 'Sound Events',
    mode: 'Mode',
    music: 'Music',
    count: 'Count',
    addItem: 'Add item',
    removeItem: 'Remove item',
    submitBill: 'Submit bill',
    alerts: 'Alerts',
    newTab: 'New tab',
    orders: 'Orders',
    recentOrders: 'Recent Orders',
    syncedToCloud: 'Synced to cloud',
    live: 'LIVE',
    cached: 'CACHED',
    noOrders: 'No synced orders yet',
    lastUpdated: 'Last updated',
    invoice: 'Invoice',
    print: 'Print',
    close: 'Close',
    edit: 'Edit',
    clear: 'Clear',
    discount: 'Discount',
    total: 'Total',
    settings: 'Settings',
    profile: 'Profile',
    logout: 'Logout',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    switchToUrdu: 'اردو میں بدلیں',
    switchToEnglish: 'Switch to English',
    clearCache: 'Clear Cache',
    superAdminOnly: 'Super Admin only',
    roles: 'Roles',
    branch: 'Branch',
    install: 'Install',
    names: 'Names',
    namesHidden: '🔒 Names hidden',
    namesVisible: '👁️ Names visible',
    customerCleared: 'Customer cleared',
    loggedOut: 'Logged out',
    logoutFailed: 'Logout failed',
    appInstalled: 'App installed! 🎉',
    cacheCleared: 'Cache cleared — reloading…',
    switchedTo: 'Switched to',
    clearCacheConfirm: 'Clear all local cache?\nPage will reload.',
    biller: 'Biller',
  },
  ur: {
    posSystem: 'پی او ایس سسٹم',
    online: 'آن لائن',
    offline: 'آف لائن',
    locked: 'مقفل',
    active: 'فعال',
    item: 'آئٹم',
    items: 'آئٹمز',
    loading: 'لوڈ ہو رہا',
    next: 'اگلا',
    cashier: 'کیشئر',
    customer: 'گاہک',
    addCustomer: 'گاہک شامل کریں',
    search: 'تلاش',
    searchPlaceholder: 'فون نمبر یا نام سے گاہک تلاش کریں…',
    noCustomerFound: 'کوئی گاہک نہیں ملا',
    addNewCustomer: 'نیا گاہک شامل کریں',
    sound: 'آواز',
    soundOn: 'آواز چالو',
    soundOff: 'آواز بند',
    soundControls: 'آواز کنٹرول',
    soundEvents: 'آواز ایونٹس',
    mode: 'موڈ',
    music: 'موسیقی',
    count: 'گنتی',
    addItem: 'آئٹم شامل کریں',
    removeItem: 'آئٹم ہٹائیں',
    submitBill: 'بل جمع کریں',
    alerts: 'الرٹس',
    newTab: 'نیا ٹیب',
    orders: 'آرڈرز',
    recentOrders: 'حالیہ آرڈرز',
    syncedToCloud: 'کلاؤڈ پر سنک',
    live: 'لائیو',
    cached: 'کیشڈ',
    noOrders: 'ابھی کوئی سنک شدہ آرڈر نہیں',
    lastUpdated: 'آخری اپڈیٹ',
    invoice: 'انوائس',
    print: 'پرنٹ',
    close: 'بند کریں',
    edit: 'ترمیم',
    clear: 'صاف کریں',
    discount: 'رعایت',
    total: 'کل',
    settings: 'ترتیبات',
    profile: 'پروفائل',
    logout: 'لاگ آؤٹ',
    lightMode: 'لائٹ موڈ',
    darkMode: 'ڈارک موڈ',
    switchToUrdu: 'اردو میں بدلیں',
    switchToEnglish: 'Switch to English',
    clearCache: 'کیشے صاف کریں',
    superAdminOnly: 'صرف سپر ایڈمن',
    roles: 'کردار',
    branch: 'برانچ',
    install: 'انسٹال',
    names: 'نام',
    namesHidden: '🔒 نام چھپا دیے',
    namesVisible: '👁️ نام ظاہر',
    customerCleared: 'گاہک صاف ہو گیا',
    loggedOut: 'لاگ آؤٹ ہو گیا',
    logoutFailed: 'لاگ آؤٹ ناکام',
    appInstalled: 'ایپ انسٹال ہو گئی! 🎉',
    cacheCleared: 'کیشے صاف ہو گیا — ری لوڈ ہو رہا…',
    switchedTo: 'تبدیل ہو گیا',
    clearCacheConfirm: 'تمام لوکل کیشے صاف کریں؟\nصفحہ ری لوڈ ہوگا۔',
    biller: 'بلر',
  },
};

const useT = (language) => useMemo(() => T[language] || T.en, [language]);

// ══════════════════════════════════════════════════════════════
// HELPERS
// ══════════════════════════════════════════════════════════════
const formatAmount = (amount) =>
  Number(amount || 0).toLocaleString('en-PK', { maximumFractionDigits: 0 });

const fmtDate = (value) => {
  const d = toSafeDate(value);
  if (!d) return '--';
  return d.toLocaleDateString('en-PK', {
    day: '2-digit', month: 'short', year: 'numeric',
  });
};

const fmtTime = (value) => {
  const d = toSafeDate(value);
  if (!d) return '--';
  return d.toLocaleTimeString('en-PK', {
    hour: '2-digit', minute: '2-digit', hour12: true,
  });
};

const ROLE_ICON_MAP = { Crown, ShieldCheck, Users, Receipt, CreditCard };

const getRoleIcon = (role) => {
  const iconName = ROLE_INFO?.[role]?.icon;
  return ROLE_ICON_MAP[iconName] || Receipt;
};

const toMs = (value) => {
  if (!value) return 0;
  try {
    if (value?.toDate) return value.toDate().getTime();
    if (value?.seconds) return value.seconds * 1000;
    if (typeof value === 'number') return value;
    const d = new Date(value);
    return isNaN(d) ? 0 : d.getTime();
  } catch { return 0; }
};

const safeJSON = (key) => {
  try { return JSON.parse(localStorage.getItem(key)); }
  catch { return null; }
};

const getCustomerLabel = (order) => {
  if (!order) return 'Walk-in';
  const c = order.customer || { name: order.customerName, phone: order.customerPhone };
  return resolveCustomerName(c);
};

// ══════════════════════════════════════════════════════════════
// ANIMATION VARIANTS
// ══════════════════════════════════════════════════════════════
const dropIn = {
  initial: { opacity: 0, y: -8, scale: 0.95 },
  animate: { opacity: 1, y: 0, scale: 1 },
  exit: { opacity: 0, y: -8, scale: 0.95 },
  transition: { type: 'spring', stiffness: 400, damping: 28 },
};

// ══════════════════════════════════════════════════════════════
// ✅ FIXED: ICON BUTTON with gold border in dark mode
// ══════════════════════════════════════════════════════════════
const IconBtn = memo(({
  icon: Icon, label, active, badge, onClick, className,
  title, disabled, isDark, size = 14, showLabel = false,
}) => (
  <motion.button
    type="button"
    onClick={onClick}
    disabled={disabled}
    whileHover={disabled ? {} : { scale: 1.04 }}
    whileTap={disabled ? {} : { scale: 0.94 }}
    title={title || label}
    className={cn(
      'relative flex items-center gap-1.5 rounded-lg transition-all duration-150 border',
      showLabel ? 'h-8 px-2.5' : 'h-8 w-8 justify-center',
      disabled && 'opacity-30 cursor-not-allowed',
      !active
        ? isDark
          ? 'border-amber-500/30 bg-white/[0.03] text-amber-400 hover:bg-amber-500/10 hover:border-amber-500/50'
          : 'border-gray-200 bg-white text-gray-700 hover:bg-gray-50 hover:border-amber-400'
        : isDark
          ? 'border-amber-500/60 bg-amber-500/15 text-amber-400 hover:bg-amber-500/25'
          : 'border-amber-400 bg-amber-50 text-amber-700 hover:bg-amber-100',
      className,
    )}
  >
    <Icon size={size} />
    {showLabel && label && (
      <span className="text-[11px] font-semibold whitespace-nowrap">{label}</span>
    )}
    {badge != null && badge !== 0 && (
      <span className={cn(
        'absolute -top-1 -right-1 flex h-4 min-w-[16px] items-center justify-center',
        'rounded-full px-1 text-[9px] font-bold border-2',
        isDark
          ? 'bg-amber-500 text-black border-[#0d0d0d]'
          : 'bg-amber-500 text-white border-white',
      )}>
        {badge}
      </span>
    )}
  </motion.button>
));
IconBtn.displayName = 'IconBtn';

// ══════════════════════════════════════════════════════════════
// REUSABLE: DROPDOWN WRAPPER
// ══════════════════════════════════════════════════════════════
const Dropdown = memo(({ open, onClose, children, className, align = 'right' }) => {
  const ref = useRef(null);

  useEffect(() => {
    if (!open) return;
    const handler = (e) => {
      if (ref.current && !ref.current.contains(e.target)) onClose?.();
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [open, onClose]);

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          ref={ref}
          {...dropIn}
          className={cn(
            'absolute top-full mt-2 z-[300]',
            align === 'right' ? 'right-0' : 'left-0',
            className,
          )}
        >
          {children}
        </motion.div>
      )}
    </AnimatePresence>
  );
});
Dropdown.displayName = 'Dropdown';

// ══════════════════════════════════════════════════════════════
// ✅ FIXED: DROPDOWN PANEL with gold border in dark
// ══════════════════════════════════════════════════════════════
const DropdownPanel = memo(({ children, isDark, className, width = 'w-64' }) => (
  <div className={cn(
    'rounded-xl border shadow-2xl overflow-hidden',
    width,
    isDark
      ? 'bg-[#1a1a1a] border-amber-500/25 shadow-black/60'
      : 'bg-white border-gray-200 shadow-gray-300/30',
    className,
  )}>
    {children}
  </div>
));
DropdownPanel.displayName = 'DropdownPanel';

// ══════════════════════════════════════════════════════════════
// DROPDOWN HEADER
// ══════════════════════════════════════════════════════════════
const DropdownHeader = memo(({ title, subtitle, icon: Icon, isDark, right, rtl }) => (
  <div className={cn(
    'flex items-center justify-between px-3.5 py-2.5 border-b',
    isDark ? 'border-amber-500/15 bg-amber-500/[0.03]' : 'border-gray-100 bg-gray-50/50',
    rtl && 'flex-row-reverse',
  )}>
    <div className={cn('flex items-center gap-2', rtl && 'flex-row-reverse')}>
      {Icon && <Icon size={13} className={isDark ? 'text-amber-400' : 'text-amber-600'} />}
      <div className={cn(rtl && 'text-right')}>
        <p className={cn('text-xs font-semibold', isDark ? 'text-white' : 'text-gray-900')}>
          {title}
        </p>
        {subtitle && (
          <p className={cn('text-[10px]', isDark ? 'text-gray-500' : 'text-gray-400')}>
            {subtitle}
          </p>
        )}
      </div>
    </div>
    {right}
  </div>
));
DropdownHeader.displayName = 'DropdownHeader';

// ══════════════════════════════════════════════════════════════
// DROPDOWN MENU ITEM
// ══════════════════════════════════════════════════════════════
const MenuItem = memo(({ icon: Icon, label, desc, onClick, isDark, danger, active, right, rtl }) => (
  <button
    type="button"
    onClick={onClick}
    className={cn(
      'flex w-full items-center gap-2.5 px-3.5 py-2 text-left transition-colors',
      rtl && 'flex-row-reverse text-right',
      danger
        ? isDark ? 'text-red-400 hover:bg-red-500/10' : 'text-red-600 hover:bg-red-50'
        : active
          ? isDark ? 'text-amber-400 bg-amber-500/8' : 'text-amber-700 bg-amber-50'
          : isDark ? 'text-gray-300 hover:bg-white/5' : 'text-gray-700 hover:bg-gray-50',
    )}
  >
    {Icon && <Icon size={14} className={cn(
      'shrink-0',
      danger ? '' : active
        ? isDark ? 'text-amber-400' : 'text-amber-600'
        : isDark ? 'text-gray-500' : 'text-gray-400',
    )} />}
    <div className={cn('flex-1 min-w-0', rtl && 'text-right')}>
      <p className="text-[13px] font-medium">{label}</p>
      {desc && (
        <p className={cn('text-[10px] mt-0.5', isDark ? 'text-gray-600' : 'text-gray-400')}>
          {desc}
        </p>
      )}
    </div>
    {right}
  </button>
));
MenuItem.displayName = 'MenuItem';

// ══════════════════════════════════════════════════════════════
// DIVIDER
// ══════════════════════════════════════════════════════════════
const Divider = ({ isDark }) => (
  <div className={cn('h-px mx-3', isDark ? 'bg-amber-500/15' : 'bg-gray-100')} />
);

// ══════════════════════════════════════════════════════════════
// STATUS CHIP
// ══════════════════════════════════════════════════════════════
const Chip = memo(({ children, color = 'gray', isDark, className }) => {
  const colors = {
    green: isDark ? 'bg-emerald-500/15 text-emerald-400 border-emerald-500/30' : 'bg-emerald-50 text-emerald-700 border-emerald-200',
    red: isDark ? 'bg-red-500/15 text-red-400 border-red-500/30' : 'bg-red-50 text-red-700 border-red-200',
    amber: isDark ? 'bg-amber-500/15 text-amber-400 border-amber-500/30' : 'bg-amber-50 text-amber-700 border-amber-200',
    blue: isDark ? 'bg-blue-500/15 text-blue-400 border-blue-500/30' : 'bg-blue-50 text-blue-700 border-blue-200',
    purple: isDark ? 'bg-purple-500/15 text-purple-400 border-purple-500/30' : 'bg-purple-50 text-purple-700 border-purple-200',
    gray: isDark ? 'bg-white/8 text-gray-400 border-gray-700' : 'bg-gray-50 text-gray-600 border-gray-200',
  };
  return (
    <span className={cn(
      'inline-flex items-center gap-1 rounded-md px-1.5 py-0.5',
      'text-[10px] font-semibold border leading-none',
      colors[color] || colors.gray,
      className,
    )}>
      {children}
    </span>
  );
});
Chip.displayName = 'Chip';

// ══════════════════════════════════════════════════════════════
// ✅ FIXED: TOP 5 LIVE ORDERS — with text label
// ══════════════════════════════════════════════════════════════
const Top5LiveBadge = memo(({
  storeId, billerId, isDark, isOnline, onViewInvoice, t, rtl,
}) => {
  const { playLog, speak } = useSound();
  const [orders, setOrders] = useState([]);
  const [loading, setLoading] = useState(true);
  const [open, setOpen] = useState(false);
  const [lastSync, setLastSync] = useState(null);
  const cacheKey = `${TOP5_CACHE_PREFIX}${storeId}_${billerId || 'all'}`;

  useEffect(() => {
    let cancelled = false;
    const cached = safeJSON(cacheKey);
    if (Array.isArray(cached) && cached.length > 0) {
      setOrders(cached);
      setLoading(false);
    }

    const loadLocal = async () => {
      if (!storeId) return;
      try {
        const recent = await getRecentOrders(storeId, 5);
        if (cancelled) return;
        if (Array.isArray(recent) && recent.length > 0) {
          const mapped = recent.map((o, idx) => ({
            id: o.firebaseId || o.localId || `local_${idx}`,
            ...o,
            _ts: toMs(o.createdAt || o.savedAt) || Date.now(),
          }));
          setOrders(mapped);
          setLoading(false);
          try { localStorage.setItem(cacheKey, JSON.stringify(mapped)); } catch { }
        }
      } catch (e) { /* ignore */ }
    };

    loadLocal();
    return () => { cancelled = true; };
  }, [cacheKey]);

  useEffect(() => {
    if (!storeId || !isOnline) { setLoading(false); return; }

    const constraints = [
      where('storeId', '==', storeId),
      orderBy('createdAt', 'desc'),
      limit(50),
    ];
    if (billerId) constraints.push(where('billerId', '==', billerId));

    const q = query(collection(db, 'orders'), ...constraints);

    const unsub = onSnapshot(
      q,
      (snap) => {
        const docs = snap.docs.map((d) => ({
          id: d.id, ...d.data(),
          _ts: toMs(d.data().createdAt) || Date.now(),
        }));
        const filtered = docs
          .filter((d) => d?.syncStatus === 'synced' || d?.synced === true)
          .sort((a, b) => (b._ts || 0) - (a._ts || 0))
          .slice(0, 5);

        setOrders((prev) => {
          if (prev.length > 0 && filtered.length > 0) {
            const prevIds = new Set(prev.map((o) => o.id));
            const newOrders = filtered.filter((o) => !prevIds.has(o.id));
            if (newOrders.length > 0) {
              try {
                playLog();
                const newest = newOrders[0];
                const serial = newest.serialNo || newest.billSerial || newest.billNo || '';
                if (serial) {
                  speak(`New order received: ${serial}`);
                }
              } catch (soundErr) {
                console.warn("[Top5LiveBadge] playLog/speak failed:", soundErr);
              }
            }
          }
          return filtered;
        });

        setLoading(false);
        setLastSync(Date.now());
        try { localStorage.setItem(cacheKey, JSON.stringify(filtered)); } catch { }
      },
      () => {
        setLoading(false);
        setTimeout(() => {
          if (!isOnline) return;
          getDocs(query(collection(db, 'orders'),
            where('storeId', '==', storeId),
            orderBy('createdAt', 'desc'), limit(50)))
            .then((snap) => {
              const allDocs = snap.docs.map((d) => ({
                id: d.id, ...d.data(),
                _ts: toMs(d.data().createdAt) || Date.now(),
              }))
                .filter((d) =>
                  (d?.syncStatus === 'synced' || d?.synced === true) &&
                  (!billerId || d.billerId === billerId))
                .sort((a, b) => (b._ts || 0) - (a._ts || 0))
                .slice(0, 5);
              setOrders(allDocs);
              try { localStorage.setItem(cacheKey, JSON.stringify(allDocs)); } catch { }
            }).catch(() => { });
        }, 2000);
      },
    );
    return () => { try { unsub(); } catch { } };
  }, [storeId, billerId, isOnline, cacheKey, playLog, speak]);

  useEffect(() => {
    if (typeof BroadcastChannel === 'undefined') return;
    const ch = new BroadcastChannel(ORDERS_CHANNEL);
    const handler = async (ev) => {
      setLastSync(Date.now());
      try {
        const data = ev?.data || ev;
        // If sync completed for a local item, remove it from local DB and optimistically show Firebase record
        if (data?.type === 'SYNC_COMPLETE' && data?.localId) {
          const { localId, firebaseId, billSerial, billSerial: serial } = data;
          try {
            // delete local record so it doesn't show in local recent list
            await localDb.orders.where('localId').equals(localId).delete();
          } catch { /* ignore */ }

          // Optimistically insert Firebase-backed record into Top5
          const optimistic = {
            id: firebaseId || localId,
            firebaseId: firebaseId || localId,
            localId,
            serialNo: billSerial || serial || `#${Date.now()}`,
            createdAt: new Date().toISOString(),
            _ts: Date.now(),
            synced: true,
            syncStatus: 'synced',
          };

          setOrders((prev) => {
            const dedup = prev.filter((o) => (o.firebaseId || o.localId) !== (firebaseId || localId));
            const next = [optimistic, ...dedup].sort((a, b) => (b._ts || 0) - (a._ts || 0)).slice(0, 5);
            try { localStorage.setItem(cacheKey, JSON.stringify(next)); } catch { }
            return next;
          });

          // Show confirmation toast
          try { toast.success(`${t.syncedToCloud} — ${optimistic.serialNo || ''}`, { duration: 2000 }); } catch { }
          try {
            playLog();
            speak(`Sync complete: ${billSerial || serial || ''}`);
          } catch (soundErr) {}
          return;
        }

        // NEW_LOCAL_ORDER: optimistic update when a local order is saved to Dexie
        if (data?.type === 'NEW_LOCAL_ORDER' && data?.order) {
          try {
            const o = data.order;
            if (!storeId || o.storeId !== storeId) return;
            const mapped = {
              id: o.firebaseId || o.localId || `local_${Date.now()}`,
              ...o,
              _ts: toMs(o.createdAt || o.savedAt) || Date.now(),
            };
            setOrders((prev) => {
              const dedup = prev.filter((p) => (p.firebaseId || p.localId) !== (o.firebaseId || o.localId));
              const next = [mapped, ...dedup].sort((a, b) => (b._ts || 0) - (a._ts || 0)).slice(0, 5);
              try { localStorage.setItem(cacheKey, JSON.stringify(next)); } catch { }
              return next;
            });
          } catch { /* ignore */ }
          return;
        }

        if (!storeId) return;
        const recent = await getRecentOrders(storeId, 5);
        if (Array.isArray(recent) && recent.length > 0) {
          const mapped = recent.map((o, idx) => ({
            id: o.firebaseId || o.localId || `local_${idx}`,
            ...o,
            _ts: toMs(o.createdAt || o.savedAt) || Date.now(),
          }));
          setOrders(mapped);
          try { localStorage.setItem(cacheKey, JSON.stringify(mapped)); } catch { }
        }
      } catch { /* ignore */ }
    };
    ch.addEventListener('message', handler);
    return () => { ch.removeEventListener('message', handler); ch.close(); };
  }, [storeId, cacheKey, t, playLog, speak]);

  return (
    <div className="relative">
      {/* ✅ Button with label */}
      <motion.button
        type="button"
        onClick={() => setOpen((v) => !v)}
        whileHover={{ scale: 1.04 }}
        whileTap={{ scale: 0.94 }}
        title={t.orders}
        className={cn(
          'relative flex items-center gap-1.5 h-8 px-2.5 rounded-lg border transition-all duration-150',
          open
            ? isDark
              ? 'border-amber-500/60 bg-amber-500/15 text-amber-400'
              : 'border-amber-400 bg-amber-50 text-amber-700'
            : isDark
              ? 'border-amber-500/30 bg-white/[0.03] text-amber-400 hover:bg-amber-500/10 hover:border-amber-500/50'
              : 'border-gray-200 bg-white text-gray-700 hover:bg-gray-50 hover:border-amber-400',
        )}
      >
        <ShoppingBag size={13} />
        <span className="text-[11px] font-semibold">{t.orders}</span>
        {!loading && orders.length > 0 && (
          <span className={cn(
            'flex h-4 min-w-[16px] items-center justify-center rounded-full px-1 text-[9px] font-bold',
            isDark ? 'bg-amber-500 text-black' : 'bg-amber-500 text-white',
          )}>
            {orders.length}
          </span>
        )}
        {isOnline && (
          <span className="h-1.5 w-1.5 rounded-full bg-emerald-500 animate-pulse" />
        )}
      </motion.button>

      <Dropdown open={open} onClose={() => setOpen(false)}>
        <DropdownPanel isDark={isDark} width="w-80">
          <DropdownHeader
            icon={ShoppingBag}
            title={t.recentOrders}
            subtitle={t.syncedToCloud}
            isDark={isDark}
            rtl={rtl}
            right={
              <div className="flex items-center gap-1.5">
                {isOnline ? (
                  <Chip color="green" isDark={isDark}>
                    <span className="h-1.5 w-1.5 rounded-full bg-emerald-400 animate-pulse" />
                    {t.live}
                  </Chip>
                ) : (
                  <Chip color="amber" isDark={isDark}>
                    <WifiOff size={8} /> {t.cached}
                  </Chip>
                )}
              </div>
            }
          />

          <div className="max-h-72 overflow-y-auto">
            {loading && (
              <div className="flex flex-col items-center py-8 gap-2">
                <Loader2 size={16} className={cn('animate-spin', isDark ? 'text-amber-400' : 'text-amber-600')} />
                <span className={cn('text-[11px]', isDark ? 'text-gray-500' : 'text-gray-400')}>
                  {t.loading}…
                </span>
              </div>
            )}

            {!loading && orders.length === 0 && (
              <div className="flex flex-col items-center py-8 gap-2">
                <Package size={24} className={cn('opacity-20', isDark ? 'text-gray-600' : 'text-gray-300')} />
                <p className={cn('text-xs', isDark ? 'text-gray-600' : 'text-gray-400')}>
                  {t.noOrders}
                </p>
              </div>
            )}

            {!loading && orders.map((order, idx) => {
              const serial = order.serialNo || order.billSerial || order.billNo || `#${idx + 1}`;
              const total = order.grandTotal || order.totalAmount || order.total || 0;

              return (
                <button
                  key={order.id || idx}
                  type="button"
                  onClick={() => { onViewInvoice?.(order); setOpen(false); }}
                  className={cn(
                    'flex w-full items-center gap-3 px-3.5 py-2.5 text-left transition-colors border-b last:border-0',
                    isDark
                      ? 'border-gray-800 hover:bg-amber-500/[0.06]'
                      : 'border-gray-50 hover:bg-amber-50/40',
                  )}
                >
                  <div className={cn(
                    'flex h-7 w-7 shrink-0 items-center justify-center rounded-lg text-[10px] font-bold',
                    isDark ? 'bg-amber-500/15 text-amber-400' : 'bg-amber-50 text-amber-700',
                  )}>
                    {idx + 1}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-1.5">
                      <span className={cn('font-mono text-[12px] font-bold', isDark ? 'text-white' : 'text-gray-900')}>
                        {serial}
                      </span>
                      <CheckCircle2 size={10} className="text-emerald-500 shrink-0" />
                    </div>
                    <div className="flex items-center gap-1.5 mt-0.5">
                      <span className={cn('text-[10px]', isDark ? 'text-gray-500' : 'text-gray-400')}>
                        {relativeTime(order.createdAt || order._ts)}
                      </span>
                      <span className={cn('text-[10px]', isDark ? 'text-gray-600' : 'text-gray-300')}>·</span>
                      <span className={cn('text-[10px] truncate', isDark ? 'text-gray-500' : 'text-gray-400')}>
                        {getCustomerLabel(order)}
                      </span>
                    </div>
                  </div>
                  <span className={cn('font-mono text-xs font-bold shrink-0', isDark ? 'text-emerald-400' : 'text-emerald-600')}>
                    Rs.{formatAmount(total)}
                  </span>
                </button>
              );
            })}
          </div>

          {lastSync && (
            <div className={cn(
              'px-3.5 py-2 border-t text-[10px]',
              isDark ? 'border-amber-500/15 text-gray-600' : 'border-gray-100 text-gray-400',
            )}>
              {t.lastUpdated} {relativeTime(lastSync)}
            </div>
          )}
        </DropdownPanel>
      </Dropdown>
    </div>
  );
});
Top5LiveBadge.displayName = 'Top5LiveBadge';

// ══════════════════════════════════════════════════════════════
// INVOICE MODAL
// ══════════════════════════════════════════════════════════════
const InvoiceModal = memo(({ order, store, onClose, isDark, t, rtl }) => {
  if (!order) return null;

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-[500] flex items-center justify-center p-4"
      style={{ background: 'rgba(0,0,0,0.7)', backdropFilter: 'blur(8px)' }}
      onClick={onClose}
      dir={rtl ? 'rtl' : 'ltr'}
    >
      <motion.div
        initial={{ scale: 0.92, opacity: 0, y: 20 }}
        animate={{ scale: 1, opacity: 1, y: 0 }}
        exit={{ scale: 0.92, opacity: 0, y: 20 }}
        transition={{ type: 'spring', stiffness: 300, damping: 25 }}
        onClick={(e) => e.stopPropagation()}
        className={cn(
          'w-full max-w-md rounded-2xl border shadow-2xl overflow-hidden',
          isDark ? 'bg-[#1a1a1a] border-amber-500/30' : 'bg-white border-gray-200',
        )}
      >
        <DropdownHeader
          icon={Receipt}
          title={t.invoice}
          subtitle={order.serialNo || order.billSerial || order.billNo || '—'}
          isDark={isDark}
          rtl={rtl}
          right={
            <button type="button" onClick={onClose}
              className={cn('rounded-lg p-1 transition', isDark ? 'hover:bg-white/10 text-gray-400' : 'hover:bg-gray-100 text-gray-500')}>
              <X size={16} />
            </button>
          }
        />

        <div className="p-4 space-y-3">
          <div className={cn('rounded-xl p-3', isDark ? 'bg-white/[0.04]' : 'bg-gray-50')}>
            <p className={cn('text-[10px] uppercase font-bold mb-1', isDark ? 'text-gray-500' : 'text-gray-400')}>
              {t.customer}
            </p>
            <p className={cn('font-semibold text-sm', isDark ? 'text-white' : 'text-gray-900')}>
              {getCustomerLabel(order)}
            </p>
            {order.customer?.phone && (
              <p className={cn('text-xs flex items-center gap-1 mt-0.5', isDark ? 'text-gray-400' : 'text-gray-500')}>
                <Phone size={9} /> {order.customer.phone}
              </p>
            )}
          </div>

          {order.items?.length > 0 && (
            <div>
              <p className={cn('text-[10px] uppercase font-bold mb-1.5', isDark ? 'text-gray-500' : 'text-gray-400')}>
                {t.items} ({order.items.length})
              </p>
              <div className="space-y-1 max-h-40 overflow-y-auto">
                {order.items.map((item, i) => (
                  <div key={i} className={cn(
                    'flex items-center justify-between text-xs rounded-lg px-2.5 py-1.5',
                    isDark ? 'bg-white/[0.03]' : 'bg-gray-50',
                  )}>
                    <span className={cn('flex-1 truncate', isDark ? 'text-gray-300' : 'text-gray-700')}>
                      {item.productName || `Item ${i + 1}`}
                      {item.qty > 1 && <span className="ml-1 opacity-50">×{item.qty}</span>}
                    </span>
                    <span className={cn('font-mono font-bold shrink-0 ml-2', isDark ? 'text-emerald-400' : 'text-emerald-600')}>
                      Rs.{formatAmount(item.amount || item.price * (item.qty || 1))}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}

          <div className={cn(
            'rounded-xl p-3 space-y-1.5',
            isDark ? 'bg-amber-500/8 border border-amber-500/20' : 'bg-amber-50 border border-amber-200',
          )}>
            {order.discount > 0 && (
              <div className="flex justify-between text-xs">
                <span className={isDark ? 'text-gray-400' : 'text-gray-500'}>{t.discount}</span>
                <span className="text-red-400 font-mono">−Rs.{formatAmount(order.discount)}</span>
              </div>
            )}
            <div className="flex justify-between items-center">
              <span className={cn('font-bold text-sm', isDark ? 'text-white' : 'text-gray-900')}>{t.total}</span>
              <span className={cn('font-mono font-bold text-lg', isDark ? 'text-emerald-400' : 'text-emerald-600')}>
                Rs.{formatAmount(order.grandTotal || order.totalAmount || order.total)}
              </span>
            </div>
          </div>
        </div>

        <div className={cn('flex gap-2 border-t px-4 py-3', isDark ? 'border-amber-500/15' : 'border-gray-100')}>
          <button type="button" onClick={() => window.print()}
            className={cn('flex-1 rounded-xl py-2.5 text-xs font-bold transition',
              isDark ? 'bg-amber-500/15 text-amber-400 hover:bg-amber-500/25' : 'bg-amber-50 text-amber-700 hover:bg-amber-100')}>
            🖨️ {t.print}
          </button>
          <button type="button" onClick={onClose}
            className={cn('flex-1 rounded-xl py-2.5 text-xs font-bold transition',
              isDark ? 'bg-white/5 text-gray-400 hover:bg-white/10' : 'bg-gray-100 text-gray-600 hover:bg-gray-200')}>
            {t.close}
          </button>
        </div>
      </motion.div>
    </motion.div>
  );
});
InvoiceModal.displayName = 'InvoiceModal';

// ══════════════════════════════════════════════════════════════
// STORE FETCH HOOK
// ══════════════════════════════════════════════════════════════
const useStoreData = (storeId, storeProp) => {
  const cacheKey = `pos_store_${storeId}`;
  const [storeData, setStoreData] = useState(() => {
    if (storeProp?.storeName || storeProp?.name) return storeProp;
    const cached = safeJSON(cacheKey);
    if (cached && (cached.storeName || cached.name) &&
      Date.now() - (cached._cachedAt || 0) < CACHE_TTL_MS) return cached;
    return null;
  });

  useEffect(() => {
    if (storeProp?.storeName || storeProp?.name) { setStoreData(storeProp); return; }
    if (!storeId || storeId === 'default' || !navigator.onLine) return;
    const unsub = onSnapshot(
      doc(db, 'stores', storeId),
      (snap) => {
        if (!snap.exists()) return;
        const data = { id: snap.id, ...snap.data(), _cachedAt: Date.now() };
        setStoreData(data);
        try { localStorage.setItem(cacheKey, JSON.stringify(data)); } catch { }
      },
      () => { },
    );
    return () => unsub();
  }, [storeId, storeProp, cacheKey]);

  return storeData;
};

// ══════════════════════════════════════════════════════════════
// SOUND ACTION TOGGLES
// ══════════════════════════════════════════════════════════════
const ACTIONS_STORAGE_KEY = 'pos_sound_actions_v1';

const ActionToggles = memo(({ isDark, t, rtl }) => {
  const defaultSettings = { insert: true, delete: true, submit: true, alert: true };
  const [settings, setSettings] = useState(() => {
    try { return JSON.parse(localStorage.getItem(ACTIONS_STORAGE_KEY)) || defaultSettings; }
    catch { return defaultSettings; }
  });

  useEffect(() => {
    try {
      localStorage.setItem(ACTIONS_STORAGE_KEY, JSON.stringify(settings));
      window.dispatchEvent(new CustomEvent('pos:soundSettingsChanged', { detail: settings }));
    } catch { }
  }, [settings]);

  const toggle = (k) => setSettings((s) => ({ ...s, [k]: !s[k] }));

  const labels = { insert: t.addItem, delete: t.removeItem, submit: t.submitBill, alert: t.alerts };
  const icons = { insert: Plus, delete: Trash2, submit: Receipt, alert: Bell };

  return (
    <div className="space-y-0.5">
      {Object.keys(settings).map((k) => {
        const Icon = icons[k];
        return (
          <button
            key={k}
            type="button"
            onClick={() => toggle(k)}
            className={cn(
              'flex w-full items-center gap-2.5 px-3 py-2 rounded-lg transition-colors',
              rtl && 'flex-row-reverse',
              settings[k]
                ? isDark ? 'text-emerald-400 bg-emerald-500/8' : 'text-emerald-700 bg-emerald-50'
                : isDark ? 'text-gray-500 hover:bg-white/[0.03]' : 'text-gray-400 hover:bg-gray-50',
            )}
          >
            <Icon size={13} className="shrink-0" />
            <span className={cn('flex-1 text-[12px] font-medium', rtl ? 'text-right' : 'text-left')}>
              {labels[k]}
            </span>
            <div className={cn(
              'h-4 w-7 rounded-full transition-all duration-200 relative',
              settings[k]
                ? 'bg-emerald-500' : isDark ? 'bg-gray-700' : 'bg-gray-300',
            )}>
              <div className={cn(
                'absolute top-0.5 h-3 w-3 rounded-full bg-white transition-all duration-200 shadow-sm',
                settings[k] ? 'left-3.5' : 'left-0.5',
              )} />
            </div>
          </button>
        );
      })}
    </div>
  );
});
ActionToggles.displayName = 'ActionToggles';

// ══════════════════════════════════════════════════════════════
// SEARCH OVERLAY
// ══════════════════════════════════════════════════════════════
const SearchOverlay = memo(({
  show, onClose, storeId, isDark, setCustomer, onOpenCustomerDialog, t, rtl,
}) => {
  const [searchQ, setSearchQ] = useState('');
  const [results, setResults] = useState([]);
  const [searching, setSearching] = useState(false);
  const inputRef = useRef(null);
  const timerRef = useRef(null);

  useEffect(() => {
    if (show) {
      setSearchQ('');
      setResults([]);
      setTimeout(() => inputRef.current?.focus(), 100);
    }
  }, [show]);

  const doSearch = useCallback(async (q) => {
    if (!q || q.length < 2) { setResults([]); setSearching(false); return; }
    setSearching(true);
    try {
      const sid = storeId || 'default';
      let res = cacheSearch(q, sid);
      if (!res.length) { await cacheLoad(sid, false); res = cacheSearch(q, sid); }
      if (!res.length && navigator.onLine) {
        const fbResults = [];
        const digits = q.replace(/\D/g, '');
        if (digits.length >= 3) {
          const snap = await getDocs(query(collection(db, 'customers'),
            where('phone', '>=', digits), where('phone', '<=', digits + '\uf8ff'),
            where('storeId', '==', sid), limit(6)));
          snap.docs.forEach((d) => {
            const data = { id: d.id, ...d.data() };
            if (isValidCustomer(data)) fbResults.push(data);
          });
        }
        const lower = q.toLowerCase();
        if (lower.length >= 2) {
          const snap = await getDocs(query(collection(db, 'customers'),
            where('nameLower', '>=', lower), where('nameLower', '<=', lower + '\uf8ff'),
            where('storeId', '==', sid), limit(6)));
          snap.docs.forEach((d) => {
            const data = { id: d.id, ...d.data() };
            if (isValidCustomer(data) && !fbResults.find((r) => r.id === data.id))
              fbResults.push(data);
          });
        }
        res = fbResults.slice(0, 10);
      }
      setResults(res.filter(isValidCustomer));
    } catch { setResults([]); }
    finally { setSearching(false); }
  }, [storeId]);

  const onInput = useCallback((e) => {
    const v = e.target.value;
    setSearchQ(v);
    clearTimeout(timerRef.current);
    if (!v) { setResults([]); return; }
    timerRef.current = setTimeout(() => doSearch(v), SEARCH_DEBOUNCE_MS);
  }, [doSearch]);

  const select = useCallback((c) => {
    const built = buildCustomerObject({ name: c.name || '', phone: c.phone || '', city: c.city || 'Karachi', market: c.market || '' });
    setCustomer?.({ name: built.name, phone: built.phone, city: built.city, market: built.market });
    toast.success(`✓ ${built.name}`, { duration: 1200 });
    onClose();
  }, [setCustomer, onClose]);

  return (
    <AnimatePresence>
      {show && (
        <motion.div
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -10 }}
          transition={{ duration: 0.15 }}
          className={cn(
            'absolute left-0 right-0 top-full z-[200] p-3',
            isDark ? 'bg-[#0d0d0d]/98 border-b border-amber-500/20' : 'bg-white/98 border-b border-gray-200',
          )}
          style={{ backdropFilter: 'blur(12px)' }}
          dir={rtl ? 'rtl' : 'ltr'}
        >
          <div className="max-w-lg mx-auto">
            <div className={cn(
              'flex items-center gap-2.5 rounded-xl border px-3 py-2 transition-all',
              isDark
                ? 'border-amber-500/30 bg-white/[0.04] focus-within:border-amber-500/60'
                : 'border-gray-200 bg-white focus-within:border-amber-500 focus-within:shadow-sm',
            )}>
              <Search size={15} className={isDark ? 'text-amber-400' : 'text-gray-400'} />
              <input
                ref={inputRef}
                type="search"
                value={searchQ}
                onChange={onInput}
                placeholder={t.searchPlaceholder}
                className={cn(
                  'flex-1 bg-transparent text-sm outline-none',
                  isDark ? 'text-white placeholder:text-gray-600' : 'text-gray-900 placeholder:text-gray-400',
                  rtl && 'text-right',
                )}
                onKeyDown={(e) => e.key === 'Escape' && onClose()}
              />
              {searching && <Loader2 size={14} className="animate-spin text-amber-500" />}
              <button type="button" onClick={onClose}
                className={cn('rounded-md p-1 transition', isDark ? 'hover:bg-white/10 text-gray-500' : 'hover:bg-gray-100 text-gray-400')}>
                <X size={14} />
              </button>
            </div>

            {results.length > 0 && (
              <div className={cn(
                'mt-2 rounded-xl border overflow-hidden max-h-64 overflow-y-auto',
                isDark ? 'border-amber-500/20 bg-[#1a1a1a]' : 'border-gray-200 bg-white',
              )}>
                {results.map((c) => (
                  <button
                    key={c.id}
                    type="button"
                    onClick={() => select(c)}
                    className={cn(
                      'w-full flex items-center gap-3 px-3 py-2.5 text-left transition-colors border-b last:border-0',
                      rtl && 'flex-row-reverse text-right',
                      isDark ? 'border-gray-800 hover:bg-amber-500/[0.06]' : 'border-gray-50 hover:bg-amber-50/40',
                    )}
                  >
                    <div className={cn(
                      'flex h-8 w-8 shrink-0 items-center justify-center rounded-lg',
                      isDark ? 'bg-amber-500/15 text-amber-400' : 'bg-amber-50 text-amber-600',
                    )}>
                      <User size={14} />
                    </div>
                    <div className="min-w-0 flex-1">
                      <p className={cn('text-sm font-semibold truncate', isDark ? 'text-white' : 'text-gray-900')}>
                        {c.name}
                      </p>
                      <p className={cn('text-[11px] flex items-center gap-1', isDark ? 'text-gray-500' : 'text-gray-400')}>
                        <Phone size={9} /> {c.phone || '—'}
                        {c.city && <span className="opacity-60">· {c.city}</span>}
                      </p>
                    </div>
                  </button>
                ))}
              </div>
            )}

            {searchQ.length >= 2 && !searching && results.length === 0 && (
              <div className={cn(
                'mt-2 rounded-xl border p-4 text-center',
                isDark ? 'border-amber-500/20 bg-[#1a1a1a]' : 'border-gray-200 bg-gray-50',
              )}>
                <p className={cn('text-xs mb-2', isDark ? 'text-gray-500' : 'text-gray-400')}>
                  {t.noCustomerFound} "{searchQ}"
                </p>
                <button
                  type="button"
                  onClick={() => { onOpenCustomerDialog?.(); onClose(); }}
                  className={cn(
                    'inline-flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-semibold transition',
                    isDark
                      ? 'bg-amber-500/15 text-amber-400 hover:bg-amber-500/25'
                      : 'bg-amber-50 text-amber-700 hover:bg-amber-100',
                  )}
                >
                  <UserPlus size={12} /> {t.addNewCustomer}
                </button>
              </div>
            )}
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
});
SearchOverlay.displayName = 'SearchOverlay';

// ══════════════════════════════════════════════════════════════
// ★ MAIN COMPONENT — BillerHeader
// ══════════════════════════════════════════════════════════════
const BillerHeader = ({
  currentBillSerial,
  nextPreviewSerial: nextPreviewSerialProp,
  screenLocked,
  currentDateTime,
  items = [],
  customer,
  setCustomer,
  onOpenCustomerDialog,
  soundEnabled,
  setSoundEnabled,
  toggleSound,
  isOnline: isOnlineProp,
  offlineCount = 0,
  billerName,
  onViewInvoice,
  onF8Press,
  canToggleCashierMode,
  cashierModeActive,
  onToggleCashierMode,
  isSuperAdmin: isSuperAdminProp,
  showDualButton = true,
  dualModeEnabled = true,
  tabs,
  activeTabId,
  onSwitchTab,
  onAddTab,
  onRemoveTab,
  canAddTab,
  storeId,
  billerId,
  store: storeProp,
  notifications = [],
  isListening = false,
  speechTranscript = '',
  soundMode = 'music',
  onToggleSpeech,
  setSoundMode,
  countingEnabled = false,
  setCountingEnabled = () => {},
  countingLang = 'ur',
  setCountingLang = () => {},
}) => {

  const { isDark, toggleTheme } = useTheme();
  const { language, toggleLanguage } = useLanguage();
  const t = useT(language);
  const rtl = language === 'ur';

  const {
    userData, currentUser, signOut,
    activeRole, setActiveRole,
    isSuperAdmin: authIsSuperAdmin,
  } = useAuth();
  const { isOnline: isOnlineHook } = useNetwork();
  const navigate = useNavigate();

  // ── Derived ────────────────────────────────────────────────
  const isOnline = isOnlineProp !== undefined ? isOnlineProp : isOnlineHook;
  const isSuperAdmin = isSuperAdminProp ?? authIsSuperAdmin ?? false;
  const activeUser = userData || currentUser || null;
  const resolvedStoreId = storeId || userData?.primaryStore || userData?.storeId || 'default';
  const resolvedStore = useStoreData(resolvedStoreId, storeProp);

  const { serial: liveSerial, ready: serialReady } = useNextSerial({
    storeId: resolvedStoreId, user: activeUser, enabled: true,
  });
  const nextPreviewSerial = liveSerial || nextPreviewSerialProp || null;

  const userRoles = useMemo(() => {
    if (Array.isArray(userData?.roles) && userData.roles.length > 0) return userData.roles;
    if (typeof userData?.role === 'string' && userData.role) return [userData.role];
    return ['biller'];
  }, [userData]);

  const currentActiveRole = activeRole || userData?.primaryRole || userData?.role || 'biller';
  const activeRoleInfo = ROLE_INFO?.[currentActiveRole] || {};
  const ActiveRoleIcon = getRoleIcon(currentActiveRole);

  const isPlaceholder = useMemo(() => {
    if (!currentBillSerial) return true;
    const s = String(currentBillSerial).trim().toLowerCase();
    return ['', '----', '....', '0000', 'loading...', 'null', 'undefined'].includes(s);
  }, [currentBillSerial]);

  const hasCustomer = useMemo(() => {
    if (!customer) return false;
    const name = (customer.name || '').trim();
    const phone = (customer.phone || '').trim();
    if (!name && !phone) return false;
    if (isAutoGeneratedName(name) && !phone) return false;
    return true;
  }, [customer]);

  // ── State ──────────────────────────────────────────────────
  const [showSearch, setShowSearch] = useState(false);
  const [showProfile, setShowProfile] = useState(false);
  const [showSettings, setShowSettings] = useState(false);
  const [showSound, setShowSound] = useState(false);
  const [showCustomer, setShowCustomer] = useState(false);
  const [showProductNames, setShowProductNames] = useState(false);
  const [invoiceOrder, setInvoiceOrder] = useState(null);
  const [deferredPrompt, setDeferredPrompt] = useState(null);
  const [showInstall, setShowInstall] = useState(false);
  const [time, setTime] = useState(new Date());
  const [dualButtonDisabled, setDualButtonDisabled] = useState(true);

  // ── Permission validation ──────────────────────────────────
  useEffect(() => {
    // Disabled when user lacks permission OR dual-mode is globally disabled
    if (canToggleCashierMode && dualModeEnabled) setDualButtonDisabled(false);
    else setDualButtonDisabled(true);
  }, [canToggleCashierMode, dualModeEnabled]);

  const bcRef = useRef(null);

  // ── Clock ──────────────────────────────────────────────────
  useEffect(() => {
    if (currentDateTime) return;
    const id = setInterval(() => setTime(new Date()), 1000);
    return () => clearInterval(id);
  }, [currentDateTime]);
  const displayTime = currentDateTime ? new Date(currentDateTime) : time;

  // ── BroadcastChannel ──────────────────────────────────────
  useEffect(() => {
    if (typeof BroadcastChannel === 'undefined') return;
    bcRef.current = new BroadcastChannel(ORDERS_CHANNEL);
    return () => bcRef.current?.close();
  }, []);

  // ── Dev helper: expose a safe delete helper to the window for quick testing
  useEffect(() => {
    try {
      window.__AONE_HELPERS__ = window.__AONE_HELPERS__ || {};
      window.__AONE_HELPERS__.deleteLocalOrder = async (localId) => {
        try {
          if (!localId) return false;
          await localDb.orders.where('localId').equals(localId).delete();
          try {
            const ch = new BroadcastChannel(ORDERS_CHANNEL);
            ch.postMessage({ type: 'LOCAL_REMOVED', localId, timestamp: Date.now() });
            ch.close();
          } catch { }
          return true;
        } catch (err) {
          // expose error for debugging
          // eslint-disable-next-line no-console
          console.warn('[deleteLocalOrder]', err);
          return false;
        }
      };
    } catch { /* ignore */ }
    return () => {
      try { if (window.__AONE_HELPERS__) delete window.__AONE_HELPERS__.deleteLocalOrder; } catch { }
    };
  }, []);

  // ── PWA install ────────────────────────────────────────────
  useEffect(() => {
    const handler = (e) => { e.preventDefault(); setDeferredPrompt(e); setShowInstall(true); };
    window.addEventListener('beforeinstallprompt', handler);
    return () => window.removeEventListener('beforeinstallprompt', handler);
  }, []);

  // ── F8 global handler ─────────────────────────────────────
  useEffect(() => {
    const handler = (e) => {
      if (e.key !== 'F8') return;
      e.preventDefault(); e.stopPropagation();
      try {
        const ch = new BroadcastChannel(BILLING_CHANNEL);
        ch.postMessage({ type: 'F8_PRESSED', timestamp: Date.now() });
        ch.close();
      } catch { }
      onF8Press?.();
    };
    window.addEventListener('keydown', handler, { capture: true, passive: false });
    return () => window.removeEventListener('keydown', handler, { capture: true });
  }, [onF8Press]);

  // ── Ctrl+M sound ──────────────────────────────────────────
  const handleSoundToggle = useCallback(() => {
    if (typeof toggleSound === 'function') { toggleSound(); return; }
    setSoundEnabled?.((p) => !p);
  }, [toggleSound, setSoundEnabled]);

  useEffect(() => {
    const handler = (e) => {
      if (e.ctrlKey && (e.key === 'm' || e.key === 'M')) {
        e.preventDefault(); handleSoundToggle();
      }
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [handleSoundToggle]);

  // ── Ctrl+F search ─────────────────────────────────────────
  useEffect(() => {
    const handler = (e) => {
      if (e.ctrlKey && (e.key === 'f' || e.key === 'F')) {
        e.preventDefault(); setShowSearch(true);
      }
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, []);

  // ── Handlers ───────────────────────────────────────────────
  const clearCustomer = useCallback(() => {
    const empty = buildCustomerObject({ name: '', phone: '' });
    setCustomer?.({ name: empty.name, phone: empty.phone, city: empty.city, market: empty.market });
    setShowCustomer(false);
    toast(t.customerCleared, { icon: '🗑️', duration: 1000 });
  }, [setCustomer, t]);

  const handleLogout = useCallback(async () => {
    try {
      await signOut?.();
      ['session', 'user', 'userData'].forEach((k) => localStorage.removeItem(k));
      toast.success(t.loggedOut);
      setShowProfile(false);
      navigate('/login', { replace: true });
    } catch { toast.error(t.logoutFailed); }
  }, [signOut, navigate, t]);

  const handleViewInvoice = useCallback((order) => {
    if (onViewInvoice) onViewInvoice(order);
    else setInvoiceOrder(order);
  }, [onViewInvoice]);

  const handleRoleSwitch = useCallback((newRole) => {
    if (!setActiveRole) return;
    const result = setActiveRole(newRole);
    if (result !== false) {
      const info = ROLE_INFO?.[newRole];
      toast.success(`${t.switchedTo} ${info?.label || newRole}`, { icon: '🔁', duration: 1500 });
    }
  }, [setActiveRole, t]);

  const handleInstall = useCallback(async () => {
    if (!deferredPrompt) return;
    deferredPrompt.prompt();
    const { outcome } = await deferredPrompt.userChoice;
    if (outcome === 'accepted') { toast.success(t.appInstalled); setShowInstall(false); }
    setDeferredPrompt(null);
  }, [deferredPrompt, t]);

  const closeAll = useCallback(() => {
    setShowProfile(false);
    setShowSettings(false);
    setShowSound(false);
    setShowCustomer(false);
  }, []);

  // ══════════════════════════════════════════════════════════
  // RENDER
  // ══════════════════════════════════════════════════════════
  return (
    <>
      <header
        className={cn(
          'sticky top-0 z-40 flex-shrink-0 select-none',
          'backdrop-blur-xl transition-colors duration-200',
          isDark
            ? 'bg-[#0d0d0d]/95 border-b border-amber-500/20'
            : 'bg-white/95 border-b border-gray-200',
        )}
        dir={rtl ? 'rtl' : 'ltr'}
      >
        {/* ══ MAIN BAR ═══════════════════════════════════════ */}
        <div className={cn(
          'flex items-center h-12 px-3 gap-2',
          rtl && 'flex-row-reverse',
        )}>

          {/* ── LEFT: Brand + Info ──────────────────────── */}
          <div className={cn(
            'flex items-center gap-2 min-w-0 flex-1',
            rtl && 'flex-row-reverse',
          )}>

            {/* Logo */}
            <div className={cn('flex items-center gap-2 shrink-0', rtl && 'flex-row-reverse')}>
              <div className={cn(
                'rounded-lg p-1.5 shadow-lg',
                'bg-gradient-to-br from-amber-500 to-orange-600',
                'shadow-amber-500/30',
              )}>
                <Gem size={14} className="text-white" />
              </div>
              <div className={cn('hidden sm:block', rtl && 'text-right')}>
                <h1 className={cn('text-[13px] font-extrabold tracking-tight leading-none',
                  isDark ? 'text-white' : 'text-gray-900')}>
                  A ONE
                </h1>
                <p className={cn('text-[8px] font-semibold uppercase tracking-[0.15em] leading-none',
                  isDark ? 'text-amber-400/70' : 'text-amber-600/70')}>
                  {t.posSystem}
                </p>
              </div>
            </div>

            {/* Separator */}
            <div className={cn('hidden md:block h-6 w-px',
              isDark ? 'bg-amber-500/20' : 'bg-gray-200')} />

            {/* Branch */}
            {resolvedStore && (
              <Chip color="blue" isDark={isDark} className="hidden md:inline-flex">
                <Building2 size={9} />
                <span className="max-w-[80px] truncate">
                  {resolvedStore.storeName || resolvedStore.name}
                </span>
              </Chip>
            )}

            {/* Serial */}
            <div className={cn(
              'hidden md:flex items-center gap-1.5 rounded-lg border px-2 py-1',
              isDark ? 'bg-amber-500/[0.06] border-amber-500/20' : 'bg-amber-50 border-amber-200',
            )}>
              <Hash size={11} className={isDark ? 'text-amber-400' : 'text-amber-600'} />
              <span className={cn('font-mono text-[11px] font-bold',
                isDark ? 'text-amber-400' : 'text-amber-700')}>
                {isPlaceholder ? (
                  <span className="opacity-60 text-[10px]">
                    {!serialReady ? (
                      <span className="inline-flex items-center gap-1">
                        <Loader2 size={9} className="animate-spin" /> …
                      </span>
                    ) : nextPreviewSerial ? `${t.next}: ${nextPreviewSerial}` : '----'}
                  </span>
                ) : currentBillSerial}
              </span>
            </div>

            {/* Status */}
            {screenLocked ? (
              <Chip color="red" isDark={isDark} className="hidden sm:inline-flex">
                <Lock size={8} /> {t.locked}
              </Chip>
            ) : (
              <Chip color="green" isDark={isDark} className="hidden sm:inline-flex">
                <Unlock size={8} /> {t.active}
              </Chip>
            )}

            {/* Item count */}
            {items.length > 0 && (
              <Chip color="amber" isDark={isDark} className="hidden lg:inline-flex">
                {items.length} {items.length !== 1 ? t.items : t.item}
              </Chip>
            )}

            {/* Clock */}
            <div className={cn(
              'hidden xl:flex items-center gap-1.5 text-[10px] font-mono tabular-nums',
              isDark ? 'text-gray-500' : 'text-gray-400',
            )}>
              <Clock size={10} />
              {fmtTime(displayTime)}
            </div>
          </div>

          {/* ── RIGHT: Controls ────────────────────────── */}
          <div className={cn('flex items-center gap-1.5', rtl && 'flex-row-reverse')}>

            {/* Network */}
            <Chip
              color={isOnline ? 'green' : 'red'}
              isDark={isDark}
              className="!h-8 !px-2 !gap-1.5"
            >
              {isOnline ? <Wifi size={11} /> : <WifiOff size={11} />}
              <span className="hidden sm:inline text-[11px]">
                {isOnline ? t.online : t.offline}
              </span>
            </Chip>

            {/* Offline sync count */}
            {offlineCount > 0 && (
              <Chip color="amber" isDark={isDark} className="!h-8 !px-2 !gap-1">
                <Database size={11} /> {offlineCount}
              </Chip>
            )}

            {/* Orders with label */}
            <Top5LiveBadge
              storeId={resolvedStoreId}
              billerId={billerId}
              isDark={isDark}
              isOnline={isOnline}
              onViewInvoice={handleViewInvoice}
              t={t}
              rtl={rtl}
            />

            {/* New Tab */}
            {onAddTab && (
              <IconBtn
                icon={Plus}
                isDark={isDark}
                onClick={onAddTab}
                disabled={!canAddTab || screenLocked}
                title={`${t.newTab} (${tabs?.length || 0}/${MAX_TABS})`}
                badge={tabs?.length > 1 ? tabs.length : null}
              />
            )}

            {/* Customer */}
            <div className="relative">
              {hasCustomer ? (
                <button
                  type="button"
                  onClick={() => { closeAll(); setShowCustomer((p) => !p); }}
                  className={cn(
                    'flex items-center gap-1.5 rounded-lg border px-2.5 h-8 transition-all',
                    isDark
                      ? 'border-emerald-500/40 bg-emerald-500/10 text-emerald-400 hover:bg-emerald-500/15'
                      : 'border-emerald-300 bg-emerald-50 text-emerald-700 hover:bg-emerald-100',
                  )}
                >
                  <User size={12} />
                  <span className="text-[11px] font-semibold max-w-[60px] truncate hidden sm:inline">
                    {resolveCustomerName(customer)}
                  </span>
                  <ChevronDown size={9} className={cn('transition-transform', showCustomer && 'rotate-180')} />
                </button>
              ) : (
                <motion.button
                  type="button"
                  onClick={onOpenCustomerDialog}
                  disabled={screenLocked}
                  whileHover={{ scale: 1.03 }}
                  whileTap={{ scale: 0.97 }}
                  className={cn(
                    'flex items-center gap-1.5 h-8 rounded-lg border px-2.5 text-[11px] font-semibold transition-all',
                    'disabled:opacity-30 disabled:cursor-not-allowed',
                    isDark
                      ? 'border-amber-500/40 bg-amber-500/10 text-amber-400 hover:bg-amber-500/20 hover:border-amber-500/60'
                      : 'border-amber-300 bg-amber-50 text-amber-700 hover:bg-amber-100',
                  )}
                >
                  <UserPlus size={12} />
                  <span className="hidden sm:inline">{t.customer}</span>
                </motion.button>
              )}

              {/* Customer dropdown */}
              <Dropdown open={showCustomer} onClose={() => setShowCustomer(false)}>
                <DropdownPanel isDark={isDark} width="w-60">
                  <div className="p-3">
                    <div className={cn('flex items-start gap-3 mb-3', rtl && 'flex-row-reverse')}>
                      <div className={cn(
                        'flex h-9 w-9 shrink-0 items-center justify-center rounded-xl',
                        isDark ? 'bg-amber-500/15 text-amber-400' : 'bg-amber-50 text-amber-600',
                      )}>
                        <User size={16} />
                      </div>
                      <div className={cn('min-w-0 flex-1', rtl && 'text-right')}>
                        <p className={cn('font-bold text-sm', isDark ? 'text-white' : 'text-gray-900')}>
                          {resolveCustomerName(customer)}
                        </p>
                        {customer?.phone && (
                          <p className={cn('text-xs flex items-center gap-1 mt-0.5',
                            isDark ? 'text-gray-400' : 'text-gray-500')}>
                            <Phone size={9} /> {customer.phone}
                          </p>
                        )}
                        {customer?.city && (
                          <p className={cn('text-xs flex items-center gap-1 mt-0.5',
                            isDark ? 'text-gray-500' : 'text-gray-400')}>
                            <MapPin size={9} /> {customer.city}
                            {customer.market && ` · ${customer.market}`}
                          </p>
                        )}
                      </div>
                    </div>
                    <div className="flex gap-2">
                      <button type="button"
                        onClick={() => { onOpenCustomerDialog?.(); setShowCustomer(false); }}
                        className={cn(
                          'flex-1 rounded-lg py-2 text-xs font-semibold transition',
                          isDark ? 'bg-amber-500/15 text-amber-400 hover:bg-amber-500/25' : 'bg-amber-50 text-amber-700 hover:bg-amber-100',
                        )}>
                        {t.edit}
                      </button>
                      <button type="button" onClick={clearCustomer}
                        className={cn(
                          'flex-1 rounded-lg py-2 text-xs font-semibold transition',
                          isDark ? 'bg-red-500/10 text-red-400 hover:bg-red-500/18' : 'bg-red-50 text-red-600 hover:bg-red-100',
                        )}>
                        {t.clear}
                      </button>
                    </div>
                  </div>
                </DropdownPanel>
              </Dropdown>
            </div>

            {/* Search */}
            <IconBtn
              icon={Search}
              isDark={isDark}
              onClick={() => setShowSearch(true)}
              title={`${t.search} (Ctrl+F)`}
            />

            {/* Sound */}
            <div className="relative">
              <IconBtn
                icon={soundEnabled ? Volume2 : VolumeX}
                isDark={isDark}
                active={soundEnabled || showSound}
                onClick={() => { closeAll(); setShowSound((p) => !p); }}
                title={`${soundEnabled ? t.soundOn : t.soundOff} (Ctrl+M)`}
              />
              <Dropdown open={showSound} onClose={() => setShowSound(false)}>
                <DropdownPanel isDark={isDark} width="w-56">
                  <DropdownHeader icon={Volume2} title={t.soundControls} isDark={isDark} rtl={rtl} />

                  {/* Master toggle */}
                  <div className={cn('px-3 py-2.5 border-b', isDark ? 'border-amber-500/15' : 'border-gray-100')}>
                    <button
                      type="button"
                      onClick={handleSoundToggle}
                      className={cn(
                        'flex w-full items-center justify-between rounded-lg px-3 py-2 transition-colors',
                        rtl && 'flex-row-reverse',
                        soundEnabled
                          ? isDark ? 'bg-amber-500/10 text-amber-400' : 'bg-amber-50 text-amber-700'
                          : isDark ? 'bg-white/[0.04] text-gray-500' : 'bg-gray-50 text-gray-500',
                      )}
                    >
                      <div className={cn('flex items-center gap-2', rtl && 'flex-row-reverse')}>
                        {soundEnabled ? <Volume2 size={14} /> : <VolumeX size={14} />}
                        <span className="text-[13px] font-semibold">
                          {soundEnabled ? t.soundOn : t.soundOff}
                        </span>
                      </div>
                      <div className={cn(
                        'h-5 w-9 rounded-full transition-all duration-200 relative',
                        soundEnabled ? 'bg-amber-500' : isDark ? 'bg-gray-700' : 'bg-gray-300',
                      )}>
                        <div className={cn(
                          'absolute top-0.5 h-4 w-4 rounded-full bg-white shadow transition-all duration-200',
                          soundEnabled ? 'left-[18px]' : 'left-0.5',
                        )} />
                      </div>
                    </button>
                  </div>

                  {/* Sound mode */}
                  <div className={cn('px-3 py-2 border-b', isDark ? 'border-amber-500/15' : 'border-gray-100')}>
                    <p className={cn('text-[10px] uppercase font-bold mb-1.5',
                      isDark ? 'text-gray-500' : 'text-gray-400', rtl && 'text-right')}>
                      {t.mode}
                    </p>
                    <div className="flex gap-1.5">
                      {[
                        { key: 'music', label: t.music, icon: Music },
                      ].map(({ key, label, icon: Icon }) => (
                        <button
                          key={key}
                          type="button"
                          onClick={() => {
                            if (soundMode === key) return;
                            // Prefer direct setter if provided for immediate UI update
                            if (typeof setSoundMode === 'function') {
                              try { setSoundMode(key); } catch { onToggleSpeech?.(); }
                            } else {
                              onToggleSpeech?.();
                            }
                          }}
                          className={cn(
                            'flex-1 flex items-center justify-center gap-1.5 rounded-lg py-2 text-[11px] font-semibold transition-colors border',
                            soundMode === key
                              ? isDark
                                ? 'bg-amber-500/15 text-amber-400 border-amber-500/40'
                                : 'bg-amber-50 text-amber-700 border-amber-300'
                              : isDark
                                ? 'text-gray-500 border-gray-700 hover:bg-white/[0.04]'
                                : 'text-gray-400 border-gray-200 hover:bg-gray-50',
                          )}
                        >
                          <Icon size={12} />
                          {label}
                        </button>
                      ))}
                    </div>

                    {/* Counting toggle: moved inside Sound dropdown to avoid header overlap */}
                    <div className={cn('px-3 py-2.5 border-b flex items-center justify-between', isDark ? 'border-amber-500/15' : 'border-gray-100')}>
                      <div className="flex items-center gap-2">
                        <Calculator size={14} className={isDark ? 'text-amber-400' : 'text-amber-600'} />
                        <span className="text-[13px] font-semibold">{countingEnabled ? 'Counting: ON' : 'Counting: OFF'}</span>
                      </div>
                      <button
                        type="button"
                        onClick={() => { setCountingEnabled(!countingEnabled); }}
                        className={cn(
                          'h-5 w-9 rounded-full transition-all duration-200 relative',
                          countingEnabled ? 'bg-amber-500' : isDark ? 'bg-gray-700' : 'bg-gray-300',
                        )}
                        title={countingEnabled ? 'Disable counting' : 'Enable counting'}
                      >
                        <div className={cn(
                          'absolute top-0.5 h-4 w-4 rounded-full bg-white shadow transition-all duration-200',
                          countingEnabled ? 'left-[18px]' : 'left-0.5',
                        )} />
                      </button>
                    </div>

                    {countingEnabled && (
                      <div className={cn('px-3 py-2 border-b flex items-center justify-between', isDark ? 'border-amber-500/15' : 'border-gray-100')}>
                        <span className="text-[11px] font-semibold flex items-center gap-1">
                          <Languages size={11} className={isDark ? 'text-amber-400' : 'text-amber-600'} />
                          <span>Voice Language / زبان</span>
                        </span>
                        <div className={cn('flex gap-1 border rounded-lg p-0.5', isDark ? 'border-gray-700 bg-black/20' : 'border-gray-200 bg-gray-50')}>
                          <button
                            type="button"
                            onClick={() => setCountingLang("ur")}
                            className={cn(
                              "px-2 py-0.5 text-[10px] rounded-md transition-all font-semibold",
                              countingLang === "ur"
                                ? "bg-amber-50 text-white shadow-sm"
                                : isDark ? "text-gray-400 hover:bg-white/[0.04]" : "text-gray-600 hover:bg-gray-200"
                            )}
                          >
                            اردو
                          </button>
                          <button
                            type="button"
                            onClick={() => setCountingLang("en")}
                            className={cn(
                              "px-2 py-0.5 text-[10px] rounded-md transition-all font-semibold",
                              countingLang === "en"
                                ? "bg-amber-50 text-white shadow-sm"
                                : isDark ? "text-gray-400 hover:bg-white/[0.04]" : "text-gray-600 hover:bg-gray-200"
                            )}
                          >
                            EN
                          </button>
                        </div>
                      </div>
                    )}
                  </div>

                  {/* Per-action toggles */}
                  <div className="py-1">
                    <p className={cn('text-[10px] uppercase font-bold px-3 py-1.5',
                      isDark ? 'text-gray-500' : 'text-gray-400', rtl && 'text-right')}>
                      {t.soundEvents}
                    </p>
                    <ActionToggles isDark={isDark} t={t} rtl={rtl} />
                  </div>
                </DropdownPanel>
              </Dropdown>
            </div>

            {/* Cashier mode */}
            {showDualButton && (
              <motion.button
                type="button"
                disabled={dualButtonDisabled}
                onClick={onToggleCashierMode}
                whileHover={dualButtonDisabled ? undefined : { scale: 1.03 }}
                whileTap={dualButtonDisabled ? undefined : { scale: 0.97 }}
                className={cn(
                  'flex items-center gap-1.5 h-8 rounded-lg border px-2.5 text-[11px] font-semibold transition-all duration-300 ease-in-out',
                  dualButtonDisabled
                    ? isDark
                      ? 'border-gray-800 bg-gray-900/40 text-gray-500 cursor-not-allowed opacity-50'
                      : 'border-gray-200 bg-gray-100/50 text-gray-400 cursor-not-allowed opacity-60'
                    : cashierModeActive
                      ? isDark
                        ? 'border-purple-500 bg-gradient-to-r from-purple-950/40 via-amber-950/30 to-purple-950/40 text-purple-300 shadow-[0_0_12px_rgba(168,85,247,0.3)] hover:shadow-[0_0_18px_rgba(168,85,247,0.55)]'
                        : 'border-purple-400 bg-purple-50 text-purple-700 shadow-sm hover:bg-purple-100'
                      : isDark
                        ? 'border-amber-500/40 bg-amber-500/5 text-amber-400/90 hover:bg-amber-500/15 hover:border-amber-500/80 hover:text-amber-300 hover:shadow-[0_0_10px_rgba(245,158,11,0.25)]'
                        : 'border-amber-200 bg-amber-50/30 text-amber-800 hover:bg-amber-50 hover:border-amber-400',
                )}
              >
                {dualButtonDisabled ? (
                  <Lock size={12} className="opacity-70" />
                ) : (
                  <CreditCard size={12} className={cn(cashierModeActive ? "text-purple-400" : "text-amber-400")} />
                )}
                <span className="hidden sm:inline">
                  {dualButtonDisabled ? 'Dual (Locked)' : (cashierModeActive ? 'Dual: ON' : 'Enable Dual')}
                </span>
              </motion.button>
            )}

            {/* SA: Name toggle */}
            {isSuperAdmin && (
              <IconBtn
                icon={showProductNames ? Eye : EyeOff}
                isDark={isDark}
                active={showProductNames}
                onClick={() => {
                  setShowProductNames((p) => !p);
                  toast(showProductNames ? t.namesHidden : t.namesVisible, { duration: 1200 });
                }}
                title={t.names}
              />
            )}

            {/* PWA Install */}
            {showInstall && (
              <IconBtn
                icon={Download}
                isDark={isDark}
                onClick={handleInstall}
                title={t.install}
              />
            )}

            {/* Separator */}
            <div className={cn('h-6 w-px mx-0.5', isDark ? 'bg-amber-500/20' : 'bg-gray-200')} />

            {/* Settings dropdown */}
            <div className="relative">
              <IconBtn icon={Settings} isDark={isDark} active={showSettings}
                onClick={() => { closeAll(); setShowSettings((p) => !p); }}
                title={t.settings} />
              <Dropdown open={showSettings} onClose={() => setShowSettings(false)}>
                <DropdownPanel isDark={isDark} width="w-52">
                  <DropdownHeader icon={Settings} title={t.settings} isDark={isDark} rtl={rtl} />
                  <div className="py-1">
                    <MenuItem isDark={isDark} icon={Languages} rtl={rtl}
                      label={language === 'en' ? t.switchToUrdu : t.switchToEnglish}
                      onClick={() => { toggleLanguage(); setShowSettings(false); }} />
                    <MenuItem isDark={isDark}
                      icon={isDark ? Sun : Moon}
                      rtl={rtl}
                      label={isDark ? t.lightMode : t.darkMode}
                      onClick={() => { toggleTheme(); setShowSettings(false); }} />
                    {isSuperAdmin && (
                      <>
                        <Divider isDark={isDark} />
                        <MenuItem isDark={isDark} icon={Trash2} danger rtl={rtl}
                          label={t.clearCache}
                          desc={t.superAdminOnly}
                          onClick={() => {
                            if (!window.confirm(t.clearCacheConfirm)) return;
                            ['aone_pos_v1', 'aone_pos_v2'].forEach((n) => indexedDB.deleteDatabase(n));
                            Object.keys(localStorage)
                              .filter((k) => k.startsWith('pos_') || k.startsWith('aone'))
                              .forEach((k) => localStorage.removeItem(k));
                            toast.success(t.cacheCleared);
                            setTimeout(() => location.reload(), 1500);
                          }} />
                      </>
                    )}
                  </div>
                </DropdownPanel>
              </Dropdown>
            </div>

            {/* Profile */}
            <div className="relative">
              <button
                type="button"
                onClick={() => { closeAll(); setShowProfile((p) => !p); }}
                className={cn(
                  'flex items-center gap-1.5 rounded-lg border p-1 pr-2 transition-all h-8',
                  rtl && 'flex-row-reverse pl-2 pr-1',
                  isDark
                    ? 'border-amber-500/30 hover:border-amber-500/50 bg-white/[0.03]'
                    : 'border-gray-200 hover:border-amber-400 bg-white',
                )}
              >
                <div className={cn(
                  'flex h-6 w-6 items-center justify-center rounded-md shrink-0',
                  'bg-gradient-to-br from-amber-500 to-orange-600',
                )}>
                  <User size={12} className="text-white" />
                </div>
                <div className={cn('hidden sm:block', rtl ? 'text-right' : 'text-left')}>
                  <p className={cn('text-[11px] font-semibold leading-tight',
                    isDark ? 'text-white' : 'text-gray-900')}>
                    {billerName || activeUser?.name || t.biller}
                  </p>
                  <div className={cn('flex items-center gap-1 mt-0.5', rtl && 'flex-row-reverse')}>
                    <ActiveRoleIcon size={8} className={isDark ? 'text-amber-400' : 'text-amber-600'} />
                    <span className={cn('text-[9px] font-semibold',
                      isDark ? 'text-amber-400/80' : 'text-amber-600/80')}>
                      {activeRoleInfo.label || currentActiveRole}
                    </span>
                  </div>
                </div>
                <ChevronDown size={10} className={cn(
                  'transition-transform shrink-0',
                  showProfile && 'rotate-180',
                  isDark ? 'text-gray-500' : 'text-gray-400',
                )} />
              </button>

              <Dropdown open={showProfile} onClose={() => setShowProfile(false)}>
                <DropdownPanel isDark={isDark} width="w-64">
                  {/* User info */}
                  <div className={cn('px-4 py-3 border-b', isDark ? 'border-amber-500/15' : 'border-gray-100')}>
                    <div className={cn('flex items-center gap-3', rtl && 'flex-row-reverse')}>
                      <div className={cn(
                        'flex h-10 w-10 items-center justify-center rounded-xl',
                        'bg-gradient-to-br from-amber-500 to-orange-600',
                      )}>
                        <User size={18} className="text-white" />
                      </div>
                      <div className={cn('min-w-0 flex-1', rtl && 'text-right')}>
                        <p className={cn('font-bold text-sm truncate',
                          isDark ? 'text-white' : 'text-gray-900')}>
                          {billerName || activeUser?.name || t.biller}
                        </p>
                        {activeUser?.email && (
                          <p className={cn('text-xs truncate',
                            isDark ? 'text-gray-500' : 'text-gray-400')}>
                            {activeUser.email}
                          </p>
                        )}
                      </div>
                    </div>
                  </div>

                  {/* Roles */}
                  <div className={cn('px-4 py-2.5 border-b', isDark ? 'border-amber-500/15' : 'border-gray-100')}>
                    <p className={cn('text-[9px] uppercase font-bold mb-2',
                      isDark ? 'text-gray-500' : 'text-gray-400', rtl && 'text-right')}>
                      {t.roles} ({userRoles.length})
                    </p>
                    <div className={cn('flex flex-wrap gap-1.5', rtl && 'flex-row-reverse')}>
                      {userRoles.map((r) => {
                        const info = ROLE_INFO?.[r] || {};
                        const Icon = getRoleIcon(r);
                        const isActive = r === currentActiveRole;
                        return (
                          <button
                            key={r}
                            type="button"
                            onClick={() => handleRoleSwitch(r)}
                            className={cn(
                              'inline-flex items-center gap-1 rounded-md border px-2 py-1 text-[10px] font-semibold transition-all',
                              isActive
                                ? isDark
                                  ? 'bg-amber-500/15 text-amber-400 border-amber-500/40'
                                  : 'bg-amber-50 text-amber-700 border-amber-300'
                                : isDark
                                  ? 'text-gray-500 border-gray-700 hover:text-gray-300 hover:bg-white/[0.04]'
                                  : 'text-gray-400 border-gray-200 hover:text-gray-700 hover:bg-gray-50',
                            )}
                          >
                            <Icon size={10} />
                            {info.label || r}
                            {isActive && <CheckCircle2 size={9} className="text-emerald-500" />}
                          </button>
                        );
                      })}
                    </div>
                  </div>

                  {/* Store info */}
                  {resolvedStore && (
                    <div className={cn('px-4 py-2.5 border-b', isDark ? 'border-amber-500/15' : 'border-gray-100')}>
                      <div className={cn('flex items-center gap-2', rtl && 'flex-row-reverse')}>
                        <Building2 size={12} className="text-blue-500 shrink-0" />
                        <span className={cn('text-xs font-semibold', isDark ? 'text-white' : 'text-gray-900')}>
                          {resolvedStore.storeName || resolvedStore.name}
                        </span>
                        {(resolvedStore.location || resolvedStore.city) && (
                          <span className={cn('text-[10px]', isDark ? 'text-gray-600' : 'text-gray-400')}>
                            · {resolvedStore.location || resolvedStore.city}
                          </span>
                        )}
                      </div>
                    </div>
                  )}

                  {/* Links */}
                  <div className="py-1">
                    <MenuItem isDark={isDark} icon={User} label={t.profile} rtl={rtl}
                      onClick={() => { navigate('/biller/profile'); setShowProfile(false); }} />
                    <MenuItem isDark={isDark} icon={Settings} label={t.settings} rtl={rtl}
                      onClick={() => { navigate('/biller/settings'); setShowProfile(false); }} />
                  </div>

                  <Divider isDark={isDark} />

                  <div className="py-1">
                    <MenuItem isDark={isDark} icon={LogOut} label={t.logout} danger rtl={rtl}
                      onClick={handleLogout} />
                  </div>
                </DropdownPanel>
              </Dropdown>
            </div>
          </div>
        </div>

        {/* ══ SPEECH STATUS ══════════════════════════════════ */}
        <AnimatePresence>
          {isListening && speechTranscript?.trim() && (
            <motion.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: 'auto', opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              className={cn(
                'overflow-hidden border-t',
                isDark ? 'border-amber-500/15 bg-amber-500/5' : 'border-gray-100 bg-amber-50/50',
              )}
            >
              <div className={cn('px-4 py-1.5 flex items-center gap-2', rtl && 'flex-row-reverse')}>
                <span className="animate-pulse text-xs">🎤</span>
                <p className={cn('text-xs italic',
                  isDark ? 'text-amber-400' : 'text-amber-700')}>
                  "{speechTranscript}"
                </p>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* ══ SEARCH OVERLAY ═════════════════════════════════ */}
        <SearchOverlay
          show={showSearch}
          onClose={() => setShowSearch(false)}
          storeId={resolvedStoreId}
          isDark={isDark}
          setCustomer={setCustomer}
          onOpenCustomerDialog={onOpenCustomerDialog}
          t={t}
          rtl={rtl}
        />
      </header>

      {/* ══ INVOICE MODAL ═══════════════════════════════════ */}
      <AnimatePresence>
        {invoiceOrder && (
          <InvoiceModal
            order={invoiceOrder}
            store={resolvedStore}
            isDark={isDark}
            onClose={() => setInvoiceOrder(null)}
            t={t}
            rtl={rtl}
          />
        )}
      </AnimatePresence>
    </>
  );
};

export default BillerHeader;