/** Roman Urdu — har setting ke neeche short working description */

export const ROLE_SETTINGS_HINTS = {
  mergeItems: 'ON = biller me same price ki items ek line me merge. OFF = har entry alag line.',
  reprintWatermark: 'ON = dubara print par COPY watermark aayega. OFF = normal invoice print.',
  showDiscountField: 'ON = biller form aur table me discount field khulegi. OFF = discount hide.',
  showProductName: 'ON = biller me Product Name field + table column dikhegi. OFF = sirf price/qty.',
  billerBaseFont: 'Biller screen ka overall font — buttons, labels, headers.',
  billerEntryFont: 'Price, qty aur entry form inputs ka font size.',
  billerTableFont: 'Bill items table (neeche list) ka font size.',
  totalFont: 'Grand total amount ka bara font size.',
  invoiceFont: 'Print invoice aur receipt ka font size.',
  cashierFont: 'Cashier pending bills list ka font — bara = asani se parhna.',
  cashierRowHeight: 'Cashier list ki row height — kam = zyada bills ek screen par.',
  managerFont: 'Manager dashboard, menu aur page headings ka font.',
  managerTable: 'Manager reports, bills table aur data lists ka font.',
  offlineCashier: 'ON = cashier par PAY BY SERIAL button + offline modal. OFF = bilkul hide.',
  offlineBiller: 'ON = biller offline direct checkout (bina collect modal). OFF = collect modal aayega.',
  offlineAutoCollect: 'ON = offline par exact amount auto fill, Enter/F8 se pay. OFF = amount type karna hoga.',
  requireCustomerName: 'ON = F8 checkout par customer name zaroori. OFF = optional.',
  requireCustomerPhone: 'ON = F8 par phone zaroori (+92 format). OFF = optional.',
  discountItemPKR: 'ON = item par Rs discount allowed. OFF = sirf % ya koi discount nahi.',
  discountItemPercent: 'ON = item par % discount allowed. OFF = sirf Rs ya band.',
  discountBillPKR: 'ON = bill summary par Rs discount field. OFF = hide.',
  discountBillPercent: 'ON = bill summary par % discount field. OFF = hide.',
  maxItemPercent: 'Item par max kitna % discount — 0 = koi limit nahi.',
  maxBillPercent: 'Poori bill par max kitna % discount — 0 = koi limit nahi.',
  maxBillPKR: 'Bill par max kitne Rs discount — 0 = koi cap nahi.',
  liveSync: 'Toggle ya slider change = turant sab PCs par apply, reload ki zaroorat nahi.',
  billerStallEnabled: 'ON = biller ruk jaye ya invoice open chhor de to alert + super admin log.',
  billerStallBillIdle: 'Bill active par kitne minute koi activity nahi → biller ko alert. 0 = band.',
  billerStallInvoice: 'Print / view invoice kitne minute open → alert. 0 = band.',
  billerStallMaxBill: 'Ek bill shuru se kitne minute se zyada → lamba bill alert. 0 = band.',
  billerStallCooldown: 'Same bill par dobara alert kitne minute baad — spam band.',
};
